import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const akrobat = localFont({
  src: [
    {
      path: "../../public/fonts/Akrobat-Regular.woff",
      weight: "500", // Standard regular for Akrobat is often 500
      style: "normal",
    },
    {
      path: "../../public/fonts/Akrobat-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/Akrobat-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Akrobat-ExtraBold.woff",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-akrobat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${akrobat.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
